% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 22-Nov-2011 18:16:05
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                       
% Heading Gain
assignin('base', 'hdgGain', 0.015); % No unit

