% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 4-Jul-2011 18:06:21
%  MATLAB version: 7.13.0.31 (R2011b)
% -------------------------------------------------------------------
                                                     

LockAppMode = mpt.Signal;
LockAppMode.RTWInfo.StorageClass = 'Auto';
LockAppMode.RTWInfo.Alias = '';
LockAppMode.RTWInfo.Alignment = -1;
LockAppMode.RTWInfo.CustomStorageClass = 'Default';
LockAppMode.Description = '';
LockAppMode.DataType = 'Enum: LockAppMode';
LockAppMode.Min = [];
LockAppMode.Max = [];
LockAppMode.DocUnits = '-';
LockAppMode.Dimensions = -1;
LockAppMode.DimensionsMode = 'Fixed';
LockAppMode.Complexity = 'real';
LockAppMode.SampleTime = -1;
LockAppMode.SamplingMode = 'Sample based';
LockAppMode.InitialValue = '';

LockDoorActFailure = mpt.Signal;
LockDoorActFailure.RTWInfo.StorageClass = 'Auto';
LockDoorActFailure.RTWInfo.Alias = '';
LockDoorActFailure.RTWInfo.Alignment = -1;
LockDoorActFailure.RTWInfo.CustomStorageClass = 'Default';
LockDoorActFailure.Description = '';
LockDoorActFailure.DataType = 'boolean';
LockDoorActFailure.Min = [];
LockDoorActFailure.Max = [];
LockDoorActFailure.DocUnits = '-';
LockDoorActFailure.Dimensions = -1;
LockDoorActFailure.DimensionsMode = 'Fixed';
LockDoorActFailure.Complexity = 'real';
LockDoorActFailure.SampleTime = -1;
LockDoorActFailure.SamplingMode = 'Sample based';
LockDoorActFailure.InitialValue = '';

LockStatus = mpt.Signal;
LockStatus.RTWInfo.StorageClass = 'Auto';
LockStatus.RTWInfo.Alias = '';
LockStatus.RTWInfo.Alignment = -1;
LockStatus.RTWInfo.CustomStorageClass = 'Default';
LockStatus.Description = '';
LockStatus.DataType = 'Enum: ActuatorStatus';
LockStatus.Min = [];
LockStatus.Max = [];
LockStatus.DocUnits = '';
LockStatus.Dimensions = -1;
LockStatus.DimensionsMode = 'Fixed';
LockStatus.Complexity = 'real';
LockStatus.SampleTime = -1;
LockStatus.SamplingMode = 'Sample based';
LockStatus.InitialValue = '';

