% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 4-Jul-2011 17:26:14
%  MATLAB version: 7.13.0.31 (R2011b)
% -------------------------------------------------------------------
                                                      

LockPos = mpt.Signal;
LockPos.RTWInfo.StorageClass = 'Auto';
LockPos.RTWInfo.Alias = '';
LockPos.RTWInfo.Alignment = -1;
LockPos.RTWInfo.CustomStorageClass = 'Default';
LockPos.Description = '';
LockPos.DataType = 'fixdt(1,16,0.01,0)';
LockPos.Min = [];
LockPos.Max = [];
LockPos.DocUnits = '';
LockPos.Dimensions = -1;
LockPos.DimensionsMode = 'auto';
LockPos.Complexity = 'auto';
LockPos.SampleTime = -1;
LockPos.SamplingMode = 'auto';
LockPos.InitialValue = '';

LockStatus = mpt.Signal;
LockStatus.RTWInfo.StorageClass = 'Auto';
LockStatus.RTWInfo.Alias = '';
LockStatus.RTWInfo.Alignment = -1;
LockStatus.RTWInfo.CustomStorageClass = 'Default';
LockStatus.Description = '';
LockStatus.DataType = 'Enum: ActuatorStatus';
LockStatus.Min = [];
LockStatus.Max = [];
LockStatus.DocUnits = '';
LockStatus.Dimensions = -1;
LockStatus.DimensionsMode = 'auto';
LockStatus.Complexity = 'auto';
LockStatus.SampleTime = -1;
LockStatus.SamplingMode = 'auto';
LockStatus.InitialValue = '';

Vehicle_Speed = mpt.Signal;
Vehicle_Speed.RTWInfo.StorageClass = 'Auto';
Vehicle_Speed.RTWInfo.Alias = '';
Vehicle_Speed.RTWInfo.Alignment = -1;
Vehicle_Speed.RTWInfo.CustomStorageClass = 'Default';
Vehicle_Speed.Description = '';
Vehicle_Speed.DataType = 'single';
Vehicle_Speed.Min = [];
Vehicle_Speed.Max = [];
Vehicle_Speed.DocUnits = '';
Vehicle_Speed.Dimensions = -1;
Vehicle_Speed.DimensionsMode = 'auto';
Vehicle_Speed.Complexity = 'auto';
Vehicle_Speed.SampleTime = -1;
Vehicle_Speed.SamplingMode = 'auto';
Vehicle_Speed.InitialValue = '';

Vehicle_Speed_Cond = mpt.Signal;
Vehicle_Speed_Cond.RTWInfo.StorageClass = 'Auto';
Vehicle_Speed_Cond.RTWInfo.Alias = '';
Vehicle_Speed_Cond.RTWInfo.Alignment = -1;
Vehicle_Speed_Cond.RTWInfo.CustomStorageClass = 'Default';
Vehicle_Speed_Cond.Description = '';
Vehicle_Speed_Cond.DataType = 'single';
Vehicle_Speed_Cond.Min = [];
Vehicle_Speed_Cond.Max = [];
Vehicle_Speed_Cond.DocUnits = '';
Vehicle_Speed_Cond.Dimensions = -1;
Vehicle_Speed_Cond.DimensionsMode = 'auto';
Vehicle_Speed_Cond.Complexity = 'auto';
Vehicle_Speed_Cond.SampleTime = -1;
Vehicle_Speed_Cond.SamplingMode = 'auto';
Vehicle_Speed_Cond.InitialValue = '';

