% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 17-May-2013 11:51:17
%  MATLAB version: 8.0.0.783 (R2012b)
% -------------------------------------------------------------------
                                           
%% Tunable parameters 
T1 = Simulink.Parameter;
T1.Value = 0.8;
T1.CoderInfo.StorageClass = 'ExportedGlobal';

T2 = Simulink.Parameter;
T2.Value = 0.7;
T2.CoderInfo.StorageClass = 'ExportedGlobal';

T4 = Simulink.Parameter;
T4.Value = 0.3;
T4.CoderInfo.StorageClass = 'ExportedGlobal';

T5 = Simulink.Parameter;
T5.Value = 0.05;
T5.CoderInfo.StorageClass = 'ExportedGlobal';

%% Non-tunable parameters
% 
N=256;
Fs = 1000; 
bw = 5.6; 

%% Model Configuration
load commonConfig;
