% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 2-Jan-2012 10:13:25
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                                

LockDoorRequest = mpt.Signal;
LockDoorRequest.RTWInfo.StorageClass = 'Auto';
LockDoorRequest.RTWInfo.Alias = '';
LockDoorRequest.RTWInfo.Alignment = -1;
LockDoorRequest.RTWInfo.CustomStorageClass = 'Default';
LockDoorRequest.Description = '';
LockDoorRequest.DataType = 'boolean';
LockDoorRequest.Min = [];
LockDoorRequest.Max = [];
LockDoorRequest.DocUnits = '';
LockDoorRequest.Dimensions = -1;
LockDoorRequest.DimensionsMode = 'auto';
LockDoorRequest.Complexity = 'auto';
LockDoorRequest.SampleTime = -1;
LockDoorRequest.SamplingMode = 'auto';
LockDoorRequest.InitialValue = '';

LockLED = mpt.Signal;
LockLED.RTWInfo.StorageClass = 'Auto';
LockLED.RTWInfo.Alias = '';
LockLED.RTWInfo.Alignment = -1;
LockLED.RTWInfo.CustomStorageClass = 'Default';
LockLED.Description = '';
LockLED.DataType = 'boolean';
LockLED.Min = [];
LockLED.Max = [];
LockLED.DocUnits = '';
LockLED.Dimensions = -1;
LockLED.DimensionsMode = 'auto';
LockLED.Complexity = 'auto';
LockLED.SampleTime = -1;
LockLED.SamplingMode = 'auto';
LockLED.InitialValue = '';

