% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 2-Jan-2012 10:12:51
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
                                                  

LockDoorActFailure = mpt.Signal;
LockDoorActFailure.RTWInfo.StorageClass = 'Auto';
LockDoorActFailure.RTWInfo.Alias = '';
LockDoorActFailure.RTWInfo.Alignment = -1;
LockDoorActFailure.RTWInfo.CustomStorageClass = 'Default';
LockDoorActFailure.Description = '';
LockDoorActFailure.DataType = 'auto';
LockDoorActFailure.Min = [];
LockDoorActFailure.Max = [];
LockDoorActFailure.DocUnits = '';
LockDoorActFailure.Dimensions = -1;
LockDoorActFailure.DimensionsMode = 'auto';
LockDoorActFailure.Complexity = 'auto';
LockDoorActFailure.SampleTime = -1;
LockDoorActFailure.SamplingMode = 'auto';
LockDoorActFailure.InitialValue = '';

LockDoorMotorCmd = mpt.Signal;
LockDoorMotorCmd.RTWInfo.StorageClass = 'Auto';
LockDoorMotorCmd.RTWInfo.Alias = '';
LockDoorMotorCmd.RTWInfo.Alignment = -1;
LockDoorMotorCmd.RTWInfo.CustomStorageClass = 'Default';
LockDoorMotorCmd.Description = '';
LockDoorMotorCmd.DataType = 'auto';
LockDoorMotorCmd.Min = [];
LockDoorMotorCmd.Max = [];
LockDoorMotorCmd.DocUnits = '';
LockDoorMotorCmd.Dimensions = -1;
LockDoorMotorCmd.DimensionsMode = 'auto';
LockDoorMotorCmd.Complexity = 'auto';
LockDoorMotorCmd.SampleTime = -1;
LockDoorMotorCmd.SamplingMode = 'auto';
LockDoorMotorCmd.InitialValue = '';

LockDoorRequest = mpt.Signal;
LockDoorRequest.RTWInfo.StorageClass = 'Auto';
LockDoorRequest.RTWInfo.Alias = '';
LockDoorRequest.RTWInfo.Alignment = -1;
LockDoorRequest.RTWInfo.CustomStorageClass = 'Default';
LockDoorRequest.Description = '';
LockDoorRequest.DataType = 'boolean';
LockDoorRequest.Min = [];
LockDoorRequest.Max = [];
LockDoorRequest.DocUnits = '';
LockDoorRequest.Dimensions = -1;
LockDoorRequest.DimensionsMode = 'auto';
LockDoorRequest.Complexity = 'auto';
LockDoorRequest.SampleTime = -1;
LockDoorRequest.SamplingMode = 'auto';
LockDoorRequest.InitialValue = '';

LockStatus = mpt.Signal;
LockStatus.RTWInfo.StorageClass = 'Auto';
LockStatus.RTWInfo.Alias = '';
LockStatus.RTWInfo.Alignment = -1;
LockStatus.RTWInfo.CustomStorageClass = 'Default';
LockStatus.Description = '';
LockStatus.DataType = 'Enum: ActuatorStatus';
LockStatus.Min = [];
LockStatus.Max = [];
LockStatus.DocUnits = '';
LockStatus.Dimensions = -1;
LockStatus.DimensionsMode = 'auto';
LockStatus.Complexity = 'auto';
LockStatus.SampleTime = -1;
LockStatus.SamplingMode = 'auto';
LockStatus.InitialValue = '';

lockDoor_cmdMotorVoltageValue = mpt.Parameter;
lockDoor_cmdMotorVoltageValue.Value = 40;
lockDoor_cmdMotorVoltageValue.RTWInfo.StorageClass = 'Auto';
lockDoor_cmdMotorVoltageValue.RTWInfo.Alias = '';
lockDoor_cmdMotorVoltageValue.RTWInfo.Alignment = -1;
lockDoor_cmdMotorVoltageValue.RTWInfo.CustomStorageClass = 'Default';
lockDoor_cmdMotorVoltageValue.Description = '';
lockDoor_cmdMotorVoltageValue.DataType = 'auto';
lockDoor_cmdMotorVoltageValue.Min = [];
lockDoor_cmdMotorVoltageValue.Max = [];
lockDoor_cmdMotorVoltageValue.DocUnits = 'Volt';

lockDoor_responseTime = mpt.Parameter;
lockDoor_responseTime.Value = 4;
lockDoor_responseTime.RTWInfo.StorageClass = 'Auto';
lockDoor_responseTime.RTWInfo.Alias = '';
lockDoor_responseTime.RTWInfo.Alignment = -1;
lockDoor_responseTime.RTWInfo.CustomStorageClass = 'Default';
lockDoor_responseTime.Description = '';
lockDoor_responseTime.DataType = 'auto';
lockDoor_responseTime.Min = [];
lockDoor_responseTime.Max = [];
lockDoor_responseTime.DocUnits = '1/2 sec';

