opts.evalCode=false;
opts.outputDir='.';
publish('description.m',opts);
publish('cd000_installation.m',opts);
publish('d01_Excel2SignalBuilder/d01_Excel2SignalBuilder.m',opts);
publish('d01_Excel2SignalBuilder/cd010_xls2SignalBuilder.m',opts);
publish('d01_Excel2SignalBuilder/cd015_xls2SignalBuilder_multiple.m',opts);
publish('d02_Excel2TruthTable/d02_Excel2TruthTable.m',opts);
publish('d02_Excel2TruthTable/cd020_xls2TruthTable.m',opts);
publish('d02_Excel2TruthTable/cd030_xls2VerificationTruthTable.m',opts);
publish('d02_Excel2TruthTable/cd035_xls2TestObjective.m',opts);
publish('d02_Excel2TruthTable/cd040_xls2RequirementBaseTestTruthTable.m',opts);
publish('d03_TestHarness/d03_TestHarness.m',opts);
publish('d03_TestHarness/cd040_makeharness.m',opts);
publish('d03_TestHarness/cd050_makeharness_compareresults.m',opts);
publish('d04_ReportGeneration/d04_ReportGeneration.m',opts);
publish('d04_ReportGeneration/cd060_runCMTDReport.m',opts);

builddocsearchdb(pwd)
