function folders = getFolders()
%% Add path for this model
folders = { ...
    'Utilities',...
    'ProjectManagement',...    
    ... % Artifacts
    'Artefacts/Code',...
    'Artefacts/CodeTest',...
    'Artefacts/ModelReview',...
    'Artefacts/ModelTest',...    
    ... % Model Advisor Setup 
    'MAConfig',...
    ... % Models 
    'Model/Scripts',...
    'Model/C_BeatDetector/F_AbsTimeStamp',...
    'Model/C_BeatDetector/F_CompFeatures',...
    'Model/C_BeatDetector/F_CompFilter',...
    'Model/C_BeatDetector/F_Level1',...
    'Model/C_BeatDetector/F_Level2',...
    'Model/C_BeatDetector/F_Level3',...
    'Model/C_BeatDetector/F_Level4',...
    'Model/C_BeatDetector/F_Level5',...
    'Model/C_BeatDetector/F_Rate',...
    'Model/C_BeatDetector/I_BeatDetector',...
    'Model/C_BeatDetector/I_BeatDetector/Tests',...    
    ... % Utilities 
    '../../Common/',...
    '../../Common/ReportTemplates'  
    
    };
end
