function folders = getFolders()
%% Add paths for this project relative to root 
folders = { ...
    'ProjectManagement',...
    ... % Artifacts
    'Artefacts/Code',...
    'Artefacts/CodeTest',...
    'Artefacts/ModelReview',...
    'Artefacts/ModelTest',...    
    ... % Model Advisor Setup 
    'MAConfig',...
    ... % Utilities 
    'Utilities',...
    '../../Common/',...
    '../../Common/ReportTemplates',...  
    ... % Models 
    'Model/C_AutoPilot/I_AutoPilot',...
    'Model/C_AutoPilot/F_Altitude_Mode_Cmp',...
    'Model/C_AutoPilot/F_Attitude_Controller_Cmp',...
    'Model/C_AutoPilot/F_Pitch_Ap_Cmp',...
    'Model/C_AutoPilot/F_Roll_Ap_Cmp',...
    'Model/C_AutoPilot/F_Yaw_Damper_Cmp',...
    'Model/C_AutoPilot/Library',...
    'Model/C_AutoPilot/Utilities',...
    'Model/Scripts'
    };

end
