function folders = getFolders()
%% Add paths for this project relative to root 
folders = { ...
    'Utilities',...
    'ProjectManagement',...
    ... % Artifacts
    'Artefacts/Code',...
    'Artefacts/CodeTest',...
    'Artefacts/ModelReview',...
    'Artefacts/ModelTest',...    
    ... % Model Advisor Setup 
    'MAConfig',...
    ... % Models 
    'Model/C_DoorLock/I_DoorLock',...
    'Model/C_DoorLock/I_DoorLock/Plant',...
    'Model/C_DoorLock/S_Types',...
    'Model/C_DoorLock/F_Actuator_Ctrl',...
    'Model/C_DoorLock/F_Actuator_Ctrl/Tests',...
    'Model/C_DoorLock/F_Input_Conditioning',...
    'Model/C_DoorLock/F_Lock_Mode_Manager',...
    'Model/C_DoorLock/F_Locking_Strategy',...
    ... % Utilities 
    '../../Common/',...
    '../../Common/ReportTemplates'  
    };

end
